In [1]:
import os
import scanpy as sc
import anndata as ad
import pandas as pd
import time 
import numpy as np
import liana as li
import itertools
import re # spliting the data 
import scipy as sci
from scipy.stats import false_discovery_control
import seaborn as sns
import matplotlib.pyplot as plt

# Analysis Start here

In [2]:
res1 = pd.read_csv("/projects/bioinformatics/DB/scRNAseq_parkinson/liana_results_sample_modified.csv")

In [3]:
res1

,disease,ligand,ligand_complex,ligand_means,ligand_props,receptor,receptor_complex,receptor_means,receptor_props,source,target,lr_means,cellphone_pvals
0,normal,NLGN1,NLGN1,5.963885,0.999125,NRXN3,NRXN3,6.199426,0.999746,oligodendrocyte precursor cell,GABAergic neuron,6.081656,0.0
1,normal,NLGN1,NLGN1,5.963885,0.999125,NRXN1,NRXN1,5.933232,0.999083,oligodendrocyte precursor cell,oligodendrocyte precursor cell,5.948559,0.0
2,normal,LRRTM4,LRRTM4,5.563381,0.997374,NRXN3,NRXN3,6.199426,0.999746,oligodendrocyte precursor cell,GABAergic neuron,5.881403,0.0
3,normal,NLGN1,NLGN1,5.963885,0.999125,NRXN1,NRXN1,5.689255,0.999367,oligodendrocyte precursor cell,glutamatergic neuron,5.826570,0.0
4,normal,NRG3,NRG3,6.036231,0.998887,ERBB4,ERBB4,5.509386,0.921737,astrocyte,GABAergic neuron,5.772809,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
65251,Parkinson disease,C5,C5,0.165941,0.103910,C5AR1,C5AR1,0.177606,0.111052,glutamatergic neuron,central nervous system neuron,0.171773,1.0
65252,Parkinson disease,WNT8A,WNT8A,0.156221,0.103258,SFRP1,SFRP1,0.187223,0.102392,central nervous system neuron,central nervous system neuron,0.171722,0.0
65253,Parkinson disease,PYY,PYY,0.170627,0.112251,NPY5R,NPY5R,0.168829,0.108387,central nervous system neuron,central nervous system neuron,0.169728,0.0
65254,Parkinson disease,HLA-A,HLA-A,0.175738,0.106003,CD8A,CD8A,0.160177,0.102710,glutamatergic neuron,glutamatergic neuron,0.167958,1.0
65255,Parkinson disease,WNT8A,WNT8A,0.156221,0.103258,FZD4,FZD4_LRP6,0.160458,0.108187,central nervous system neuron,central nervous system neuron,0.158340,0.0

In [4]:
# apply FDR correction
res1["cellphone_fdr"] = false_discovery_control(
    res1["cellphone_pvals"].values,
    method="bh"
    
)

In [5]:
res1

,disease,ligand,ligand_complex,ligand_means,ligand_props,receptor,receptor_complex,receptor_means,receptor_props,source,target,lr_means,cellphone_pvals,cellphone_fdr
0,normal,NLGN1,NLGN1,5.963885,0.999125,NRXN3,NRXN3,6.199426,0.999746,oligodendrocyte precursor cell,GABAergic neuron,6.081656,0.0,0.0
1,normal,NLGN1,NLGN1,5.963885,0.999125,NRXN1,NRXN1,5.933232,0.999083,oligodendrocyte precursor cell,oligodendrocyte precursor cell,5.948559,0.0,0.0
2,normal,LRRTM4,LRRTM4,5.563381,0.997374,NRXN3,NRXN3,6.199426,0.999746,oligodendrocyte precursor cell,GABAergic neuron,5.881403,0.0,0.0
3,normal,NLGN1,NLGN1,5.963885,0.999125,NRXN1,NRXN1,5.689255,0.999367,oligodendrocyte precursor cell,glutamatergic neuron,5.826570,0.0,0.0
4,normal,NRG3,NRG3,6.036231,0.998887,ERBB4,ERBB4,5.509386,0.921737,astrocyte,GABAergic neuron,5.772809,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65251,Parkinson disease,C5,C5,0.165941,0.103910,C5AR1,C5AR1,0.177606,0.111052,glutamatergic neuron,central nervous system neuron,0.171773,1.0,1.0
65252,Parkinson disease,WNT8A,WNT8A,0.156221,0.103258,SFRP1,SFRP1,0.187223,0.102392,central nervous system neuron,central nervous system neuron,0.171722,0.0,0.0
65253,Parkinson disease,PYY,PYY,0.170627,0.112251,NPY5R,NPY5R,0.168829,0.108387,central nervous system neuron,central nervous system neuron,0.169728,0.0,0.0
65254,Parkinson disease,HLA-A,HLA-A,0.175738,0.106003,CD8A,CD8A,0.160177,0.102710,glutamatergic neuron,glutamatergic neuron,0.167958,1.0,1.0
65255,Parkinson disease,WNT8A,WNT8A,0.156221,0.103258,FZD4,FZD4_LRP6,0.160458,0.108187,central nervous system neuron,central nervous system neuron,0.158340,0.0,0.0

In [6]:
# filter properly (those that are significant!)

significant_lr = res1[
    (res1["cellphone_fdr"] < 0.05) &
    (res1["ligand_props"] > 0.1) &
    (res1["receptor_props"] > 0.1)
]

In [7]:
significant_lr

,disease,ligand,ligand_complex,ligand_means,ligand_props,receptor,receptor_complex,receptor_means,receptor_props,source,target,lr_means,cellphone_pvals,cellphone_fdr
0,normal,NLGN1,NLGN1,5.963885,0.999125,NRXN3,NRXN3,6.199426,0.999746,oligodendrocyte precursor cell,GABAergic neuron,6.081656,0.0,0.0
1,normal,NLGN1,NLGN1,5.963885,0.999125,NRXN1,NRXN1,5.933232,0.999083,oligodendrocyte precursor cell,oligodendrocyte precursor cell,5.948559,0.0,0.0
2,normal,LRRTM4,LRRTM4,5.563381,0.997374,NRXN3,NRXN3,6.199426,0.999746,oligodendrocyte precursor cell,GABAergic neuron,5.881403,0.0,0.0
3,normal,NLGN1,NLGN1,5.963885,0.999125,NRXN1,NRXN1,5.689255,0.999367,oligodendrocyte precursor cell,glutamatergic neuron,5.826570,0.0,0.0
4,normal,NRG3,NRG3,6.036231,0.998887,ERBB4,ERBB4,5.509386,0.921737,astrocyte,GABAergic neuron,5.772809,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65248,Parkinson disease,HLA-F,HLA-F,0.192334,0.100483,CD8A,CD8A,0.160177,0.102710,GABAergic neuron,glutamatergic neuron,0.176255,0.0,0.0
65250,Parkinson disease,WNT8A,WNT8A,0.156221,0.103258,FRZB,FRZB,0.189166,0.113783,central nervous system neuron,central nervous system neuron,0.172694,0.0,0.0
65252,Parkinson disease,WNT8A,WNT8A,0.156221,0.103258,SFRP1,SFRP1,0.187223,0.102392,central nervous system neuron,central nervous system neuron,0.171722,0.0,0.0
65253,Parkinson disease,PYY,PYY,0.170627,0.112251,NPY5R,NPY5R,0.168829,0.108387,central nervous system neuron,central nervous system neuron,0.169728,0.0,0.0
65255,Parkinson disease,WNT8A,WNT8A,0.156221,0.103258,FZD4,FZD4_LRP6,0.160458,0.108187,central nervous system neuron,central nervous system neuron,0.158340,0.0,0.0

In [8]:
df = significant_lr

In [9]:
df.groupby("disease").size()

disease
Parkinson disease    21751
normal               21682
dtype: int64

In [10]:
df.groupby(["disease", "source", "target"]).size().sort_values(ascending=False)

disease            source                         target
normal             central nervous system neuron  central nervous system neuron    444
Parkinson disease  central nervous system neuron  central nervous system neuron    434
normal             central nervous system neuron  glutamatergic neuron             434
Parkinson disease  central nervous system neuron  glutamatergic neuron             410
normal             central nervous system neuron  GABAergic neuron                 398
                                                                                  ...
Parkinson disease  leukocyte                      endothelial cell                  26
                                                  ependymal cell                    22
normal             leukocyte                      ependymal cell                    15
                                                  oligodendrocyte                   14
Parkinson disease  leukocyte                      oligodendrocyte                   13
Length: 242, dtype: int64

In [11]:
df.groupby(["disease", "ligand", "receptor"]).size().sort_values(ascending=False)

disease            ligand   receptor
Parkinson disease  WNT5B    FZD6        108
normal             WNT5B    FZD6         99
Parkinson disease  BMP6     ACVR2A       98
normal             BMP6     ACVR2A       93
Parkinson disease  BMP6     ACVR2B       90
                                       ...
normal             ICAM3    ITGAL         1
                            ITGB2         1
Parkinson disease  CDH5     CDH5          1
                   COL10A1  ITGA2         1
                   CBR1     PTGER3        1
Length: 2538, dtype: int64

# Matching the same interaction

In [12]:
interaction_cols = [
    "source",
    "target",
    "ligand",
    "receptor"
]

df["interaction"] = (
    df[interaction_cols]
    .astype(str)
    .agg("|".join, axis=1)
)

/var/tmp/pbs.441868.pbs01/ipykernel_299438/3501416028.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

## To see how many interactions exist in each condition

In [13]:
df.groupby("disease")["interaction"].nunique()

disease
Parkinson disease    20435
normal               20397
Name: interaction, dtype: int64

## interactions present in both normal and PD

In [14]:
normal_interactions = set(
    df.loc[df["disease"] == "normal", "interaction"]
)

pd_interactions = set(
    df.loc[df["disease"] == "Parkinson disease", "interaction"]
)

common_interactions = normal_interactions & pd_interactions

print("Normal:", len(normal_interactions))
print("PD:", len(pd_interactions))
print("Common:", len(common_interactions))

Normal: 20397
PD: 20435
Common: 18229

## calculate PD vs normal change

In [15]:
comparison = (
    df[df["interaction"].isin(common_interactions)]
    .pivot_table(
        index=["source", "target", "ligand", "receptor"],
        columns="disease",
        values="lr_means",
        aggfunc="mean"
    )
    .reset_index()
)

comparison["delta_lr"] = (
    comparison["Parkinson disease"]
    - comparison["normal"]
)

eps = 1e-6

comparison["log2FC"] = np.log2(
    (comparison["Parkinson disease"] + eps) /
    (comparison["normal"] + eps)
)

comparison.sort_values("log2FC").head(20)

disease,source,target,ligand,receptor,Parkinson disease,normal,delta_lr,log2FC
10283,ependymal cell,oligodendrocyte,LPAR3,ADGRE5,0.435072,0.828959,-0.393887,-0.930046
8809,ependymal cell,GABAergic neuron,ANGPT1,TEK,0.567514,1.065021,-0.497507,-0.908153
7481,central nervous system neuron,oligodendrocyte precursor cell,SST,SSTR1,0.307641,0.568597,-0.260955,-0.886154
6384,central nervous system neuron,ependymal cell,WNT8A,FRZB,0.249228,0.456817,-0.207589,-0.874146
9247,ependymal cell,central nervous system neuron,ANGPT1,TEK,0.611273,1.114476,-0.503203,-0.866476
10176,ependymal cell,mural cell,LPAR3,ADGRE5,0.485478,0.881011,-0.395533,-0.859753
3043,astrocyte,central nervous system neuron,SEMA4A,NRP1,0.484960,0.872093,-0.387133,-0.846615
9763,ependymal cell,glutamatergic neuron,ANGPT1,TEK,0.615402,1.104593,-0.489191,-0.843913
11387,glutamatergic neuron,central nervous system neuron,VEGFB,NRP1,0.424925,0.759489,-0.334564,-0.837820
936,GABAergic neuron,central nervous system neuron,VEGFB,NRP1,0.501262,0.892081,-0.390819,-0.831608
6373,central nervous system neuron,ependymal cell,WNT4,FRZB,0.270125,0.477703,-0.207578,-0.822487
892,GABAergic neuron,central nervous system neuron,SEMA3A,NRP1,0.448485,0.784372,-0.335886,-0.806475
5829,central nervous system neuron,central nervous system neuron,SEMA3D,NRP1,0.552964,0.956797,-0.403833,-0.791026
3396,astrocyte,ependymal cell,WNT7A,FRZB,0.306764,0.515958,-0.209194,-0.750124
1352,GABAergic neuron,ependymal cell,WNT3,FRZB,0.315901,0.531051,-0.215150,-0.749376
1357,GABAergic neuron,ependymal cell,WNT5B,FRZB,0.341861,0.572296,-0.230435,-0.743351
17392,oligodendrocyte precursor cell,ependymal cell,WNT5A,FRZB,0.341417,0.569642,-0.228225,-0.738520
3390,astrocyte,ependymal cell,WNT5B,FRZB,0.311502,0.519583,-0.208082,-0.738113
15872,oligodendrocyte,ependymal cell,WNT2B,FRZB,0.315941,0.523657,-0.207716,-0.728965
14370,mural cell,ependymal cell,WNT4,FRZB,0.328586,0.544188,-0.215601,-0.727830

## Which interactions are decreased in PD?

In [16]:
comparison.sort_values("log2FC").head(30)

disease,source,target,ligand,receptor,Parkinson disease,normal,delta_lr,log2FC
10283,ependymal cell,oligodendrocyte,LPAR3,ADGRE5,0.435072,0.828959,-0.393887,-0.930046
8809,ependymal cell,GABAergic neuron,ANGPT1,TEK,0.567514,1.065021,-0.497507,-0.908153
7481,central nervous system neuron,oligodendrocyte precursor cell,SST,SSTR1,0.307641,0.568597,-0.260955,-0.886154
6384,central nervous system neuron,ependymal cell,WNT8A,FRZB,0.249228,0.456817,-0.207589,-0.874146
9247,ependymal cell,central nervous system neuron,ANGPT1,TEK,0.611273,1.114476,-0.503203,-0.866476
10176,ependymal cell,mural cell,LPAR3,ADGRE5,0.485478,0.881011,-0.395533,-0.859753
3043,astrocyte,central nervous system neuron,SEMA4A,NRP1,0.484960,0.872093,-0.387133,-0.846615
9763,ependymal cell,glutamatergic neuron,ANGPT1,TEK,0.615402,1.104593,-0.489191,-0.843913
11387,glutamatergic neuron,central nervous system neuron,VEGFB,NRP1,0.424925,0.759489,-0.334564,-0.837820
936,GABAergic neuron,central nervous system neuron,VEGFB,NRP1,0.501262,0.892081,-0.390819,-0.831608
6373,central nervous system neuron,ependymal cell,WNT4,FRZB,0.270125,0.477703,-0.207578,-0.822487
892,GABAergic neuron,central nervous system neuron,SEMA3A,NRP1,0.448485,0.784372,-0.335886,-0.806475
5829,central nervous system neuron,central nervous system neuron,SEMA3D,NRP1,0.552964,0.956797,-0.403833,-0.791026
3396,astrocyte,ependymal cell,WNT7A,FRZB,0.306764,0.515958,-0.209194,-0.750124
1352,GABAergic neuron,ependymal cell,WNT3,FRZB,0.315901,0.531051,-0.215150,-0.749376
1357,GABAergic neuron,ependymal cell,WNT5B,FRZB,0.341861,0.572296,-0.230435,-0.743351
17392,oligodendrocyte precursor cell,ependymal cell,WNT5A,FRZB,0.341417,0.569642,-0.228225,-0.738520
3390,astrocyte,ependymal cell,WNT5B,FRZB,0.311502,0.519583,-0.208082,-0.738113
15872,oligodendrocyte,ependymal cell,WNT2B,FRZB,0.315941,0.523657,-0.207716,-0.728965
14370,mural cell,ependymal cell,WNT4,FRZB,0.328586,0.544188,-0.215601,-0.727830
11385,glutamatergic neuron,central nervous system neuron,VEGFA,NRP1,0.480685,0.789118,-0.308433,-0.715147
5880,central nervous system neuron,central nervous system neuron,VEGFB,NRP1,0.575913,0.940183,-0.364270,-0.707090
893,GABAergic neuron,central nervous system neuron,SEMA4A,NRP1,0.477825,0.779687,-0.301862,-0.706412
934,GABAergic neuron,central nervous system neuron,VEGFA,NRP1,0.517860,0.843054,-0.325194,-0.703061
5851,central nervous system neuron,central nervous system neuron,SST,SSTR1,0.315774,0.513865,-0.198091,-0.702495
13911,mural cell,central nervous system neuron,PGF,NRP1,0.515600,0.828951,-0.313350,-0.685032
17047,oligodendrocyte precursor cell,central nervous system neuron,VEGFB,NRP1,0.565562,0.907546,-0.341985,-0.682286
9445,ependymal cell,central nervous system neuron,VEGFB,NRP1,0.528189,0.844027,-0.315839,-0.676235
5878,central nervous system neuron,central nervous system neuron,VEGFA,NRP1,0.517632,0.826230,-0.308599,-0.674617
11823,glutamatergic neuron,ependymal cell,WNT5B,FRZB,0.377559,0.601025,-0.223467,-0.670724

## Which interactions are increased?

In [17]:
comparison.sort_values("log2FC", ascending=False).head(30)

disease,source,target,ligand,receptor,Parkinson disease,normal,delta_lr,log2FC
9280,ependymal cell,central nervous system neuron,COL27A1,ITGA10,0.769439,0.418248,0.351191,0.879446
9492,ependymal cell,endothelial cell,COL27A1,ITGA10,1.137469,0.642068,0.495401,0.825029
9743,ependymal cell,ependymal cell,UBASH3B,ESR1,1.102945,0.640690,0.462255,0.783661
9798,ependymal cell,glutamatergic neuron,COL27A1,ITGA11,0.842766,0.499984,0.342782,0.753248
8842,ependymal cell,GABAergic neuron,COL27A1,ITGA1,0.857062,0.525627,0.331435,0.705359
15843,oligodendrocyte,ependymal cell,RELN,ITGA3,0.688487,0.423725,0.264762,0.700300
3116,astrocyte,endothelial cell,COL27A1,ITGA10,1.241891,0.782603,0.459288,0.666185
8264,endothelial cell,ependymal cell,TNXB,ITGA8,0.716391,0.457518,0.258874,0.646919
2883,astrocyte,central nervous system neuron,COL27A1,ITGA10,0.873861,0.558783,0.315078,0.645114
3386,astrocyte,ependymal cell,UBASH3B,ESR1,1.107334,0.710829,0.396505,0.639516
3693,astrocyte,leukocyte,PTGES3,PTGER4,1.318162,0.849185,0.468978,0.634377
9624,ependymal cell,ependymal cell,COL27A1,ITGA11,0.878008,0.578422,0.299586,0.602110
10090,ependymal cell,mural cell,COL27A1,ITGA11,1.385639,0.922435,0.463204,0.587032
9990,ependymal cell,leukocyte,COL27A1,ITGA1,1.273341,0.854125,0.419216,0.576099
16130,oligodendrocyte,mural cell,RELN,ITGA3,0.554993,0.373738,0.181255,0.570440
3433,astrocyte,glutamatergic neuron,COL27A1,ITGA11,0.947188,0.640519,0.306669,0.564408
8251,endothelial cell,ependymal cell,SEMA3F,PLXNA1,0.671412,0.454568,0.216845,0.562703
3769,astrocyte,mural cell,EGF,ERBB2,0.419965,0.284584,0.135381,0.561412
7857,endothelial cell,central nervous system macrophage,SEMA3F,PLXNA1,0.702529,0.476468,0.226060,0.560175
16050,oligodendrocyte,leukocyte,PTGES3,PTGER4,1.392542,0.949113,0.443430,0.553069
5805,central nervous system neuron,central nervous system neuron,PENK,OPRD1,0.466432,0.318518,0.147914,0.550290
15669,oligodendrocyte,central nervous system neuron,RELN,VLDLR,0.661938,0.452072,0.209866,0.550141
10043,ependymal cell,leukocyte,PTGES3,PTGER4,1.751159,1.197154,0.554004,0.548700
9340,ependymal cell,central nervous system neuron,JAM2,ITGA4,0.601258,0.412134,0.189123,0.544868
15479,oligodendrocyte,astrocyte,RELN,LRP8,0.686897,0.473166,0.213731,0.537746
3692,astrocyte,leukocyte,PTGES3,PTGER2,1.264449,0.872648,0.391801,0.535036
2406,astrocyte,GABAergic neuron,COL27A1,ITGA1,0.961484,0.666162,0.295322,0.529389
9482,ependymal cell,endothelial cell,COL18A1,ITGA10,0.764762,0.531279,0.233483,0.525539
8071,endothelial cell,endothelial cell,GJA1,GJA1,1.405117,0.979363,0.425754,0.520774
9740,ependymal cell,ependymal cell,TNXB,ITGA8,0.579421,0.404169,0.175252,0.519652

look at ligand_props and receptor_props too

Don't only look at lr_means.

In [18]:
comparison = (
    df[df["interaction"].isin(common_interactions)]
    .pivot_table(
        index=["source", "target", "ligand", "receptor"],
        columns="disease",
        values=[
            "lr_means",
            "ligand_means",
            "ligand_props",
            "receptor_means",
            "receptor_props"
        ],
        aggfunc="mean"
    )
)

In [19]:
comparison

                                                                                   ligand_means  \
disease                                                                       Parkinson disease
source                         target                         ligand receptor
GABAergic neuron               GABAergic neuron               ACHE   CHRM1             0.212063
                                                                     CHRM2             0.212063
                                                                     CHRM3             0.212063
                                                              ANGPT1 TEK               0.659557
                                                              ANGPT2 TEK               0.526444
...                                                                                         ...
oligodendrocyte precursor cell oligodendrocyte precursor cell WNT5A  FZD9              0.340598
                                                                     LRP5              0.340598
                                                                     MCAM              0.340598
                                                                     ROR2              0.340598
                                                                     SFRP4             0.340598

                                                                                         \
disease                                                                          normal
source                         target                         ligand receptor
GABAergic neuron               GABAergic neuron               ACHE   CHRM1     0.246222
                                                                     CHRM2     0.246222
                                                                     CHRM3     0.246222
                                                              ANGPT1 TEK       0.623081
                                                              ANGPT2 TEK       0.666031
...                                                                                 ...
oligodendrocyte precursor cell oligodendrocyte precursor cell WNT5A  FZD9      0.392573
                                                                     LRP5      0.392574
                                                                     MCAM      0.392574
                                                                     ROR2      0.392574
                                                                     SFRP4     0.392574

                                                                                   ligand_props  \
disease                                                                       Parkinson disease
source                         target                         ligand receptor
GABAergic neuron               GABAergic neuron               ACHE   CHRM1             0.113104
                                                                     CHRM2             0.113104
                                                                     CHRM3             0.113104
                                                              ANGPT1 TEK               0.243034
                                                              ANGPT2 TEK               0.256424
...                                                                                         ...
oligodendrocyte precursor cell oligodendrocyte precursor cell WNT5A  FZD9              0.138634
                                                                     LRP5              0.138634
                                                                     MCAM              0.138634
                                                                     ROR2              0.138634
                                                                     SFRP4             0.138634

                                                                                         \
disease                                                                          normal
source                         target                         ligand receptor
GABAergic neuron               GABAergic neuron               ACHE   CHRM1     0.136366
                                                                     CHRM2     0.136366
                                                                     CHRM3     0.136366
                                                              ANGPT1 TEK       0.237927
                                                              ANGPT2 TEK       0.320544
...                                                                                 ...
oligodendrocyte precursor cell oligodendrocyte precursor cell WNT5A  FZD9      0.163471
                                                                     LRP5      0.163471
                                                                     MCAM      0.163471
                                                                     ROR2      0.163471
                                                                     SFRP4     0.163471

                                                                                       lr_means  \
disease                                                                       Parkinson disease
source                         target                         ligand receptor
GABAergic neuron               GABAergic neuron               ACHE   CHRM1             0.241181
                                                                     CHRM2             0.710011
                                                                     CHRM3             1.768273
                                                              ANGPT1 TEK               0.466800
                                                              ANGPT2 TEK               0.400244
...                                                                                         ...
oligodendrocyte precursor cell oligodendrocyte precursor cell WNT5A  FZD9              0.321264
                                                                     LRP5              0.374866
                                                                     MCAM              0.366398
                                                                     ROR2              0.345733
                                                                     SFRP4             0.382580

                                                                                         \
disease                                                                          normal
source                         target                         ligand receptor
GABAergic neuron               GABAergic neuron               ACHE   CHRM1     0.298248
                                                                     CHRM2     0.750937
                                                                     CHRM3     1.808889
                                                              ANGPT1 TEK       0.458608
                                                              ANGPT2 TEK       0.480082
...                                                                                 ...
oligodendrocyte precursor cell oligodendrocyte precursor cell WNT5A  FZD9      0.364028
                                                                     LRP5      0.410361
                                                                     MCAM      0.463410
                                                                     ROR2      0.396867
                                                                     SFRP4     0.463460

                                                                                 receptor_means  \
disease                                                                       Parkinson disease
source                         target                         ligand receptor
GABAergic neuron               GABAergic neuron               ACHE   CHRM1             0.270299
                                                                     CHRM2             1.207960
                                                                     CHRM3             3.324483
                                                              ANGPT1 TEK               0.274043
                                                              ANGPT2 TEK               0.274043
...                                                                                         ...
oligodendrocyte precursor cell oligodendrocyte precursor cell WNT5A  FZD9              0.301930
                                                                     LRP5              0.409134
                                                                     MCAM              0.392197
                                                                     ROR2              0.350867
                                                                     SFRP4             0.424561

                                                                                         \
disease                                                                          normal
source                         target                         ligand receptor
GABAergic neuron               GABAergic neuron               ACHE   CHRM1     0.350273
                                                                     CHRM2     1.255652
                                                                     CHRM3     3.371555
                                                              ANGPT1 TEK       0.294134
                                                              ANGPT2 TEK       0.294134
...                                                                                 ...
oligodendrocyte precursor cell oligodendrocyte precursor cell WNT5A  FZD9      0.335482
                                                                     LRP5      0.428148
                                                                     MCAM      0.534246
                                                                     ROR2      0.401161
                                                                     SFRP4     0.534346

                                                                                 receptor_props  \
disease                                                                       Parkinson disease
source                         target                         ligand receptor
GABAergic neuron               GABAergic neuron               ACHE   CHRM1             0.145789
                                                                     CHRM2             0.385550
                                                                     CHRM3             0.766605
                                                              ANGPT1 TEK               0.125862
                                                              ANGPT2 TEK               0.125862
...                                                                                         ...
oligodendrocyte precursor cell oligodendrocyte precursor cell WNT5A  FZD9              0.121815
                                                                     LRP5              0.165318
                                                                     MCAM              0.157834
                                                                     ROR2              0.128486
                                                                     SFRP4             0.163828


disease                                                                          normal
source                         target                         ligand receptor
GABAergic neuron               GABAergic neuron               ACHE   CHRM1     0.195035
                                                                     CHRM2     0.415969
                                                                     CHRM3     0.790093
                                                              ANGPT1 TEK       0.142219
                                                              ANGPT2 TEK       0.142219
...                                                                                 ...
oligodendrocyte precursor cell oligodendrocyte precursor cell WNT5A  FZD9      0.138421
                                                                     LRP5      0.177851
                                                                     MCAM      0.215322
                                                                     ROR2      0.149383
                                                                     SFRP4     0.209945

[18229 rows x 10 columns]

## Which cell populations change their communication in Parkinson's?

Calculate the mean interaction score by source and target:

In [20]:
celltype_summary = (
    df.groupby(
        ["disease", "source", "target"]
    )["lr_means"]
    .agg(
        mean="mean",
        median="median",
        count="count"
    )
    .reset_index()
)

celltype_summary.head()

,disease,source,target,mean,median,count
0,Parkinson disease,GABAergic neuron,GABAergic neuron,1.438220,0.876363,317
1,Parkinson disease,GABAergic neuron,astrocyte,1.412555,1.124030,280
2,Parkinson disease,GABAergic neuron,central nervous system macrophage,1.117717,0.843121,123
3,Parkinson disease,GABAergic neuron,central nervous system neuron,1.375114,0.936008,356
4,Parkinson disease,GABAergic neuron,endothelial cell,1.307053,1.177849,209

# Does Parkinson's have fewer or more inferred communication interactions?

In [21]:
interaction_counts = (
    df.groupby("disease")
      .apply(lambda x: x[["source", "target", "ligand", "receptor"]]
             .drop_duplicates()
             .shape[0])
)

interaction_counts

/var/tmp/pbs.441868.pbs01/ipykernel_299438/2455070064.py:3: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.

disease
Parkinson disease    20435
normal               20397
dtype: int64